<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Google_Search_Textbox</name>
   <tag></tag>
   <elementGuidId>beeddf20-6725-467d-bad3-cf8d531f6cf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name=&quot;q&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name=&quot;q&quot;]</value>
      <webElementGuid>301a2683-af8d-45d3-924b-627d959ecc8a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
