<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckList1</name>
   <tag></tag>
   <elementGuidId>c738a7a3-adee-46bc-986f-74444e4b1b35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id=&quot;checkboxes&quot;</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id=&quot;checkboxes&quot;</value>
      <webElementGuid>8339fefd-1402-4e93-bb1b-2369f5f8c89c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
