<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox</name>
   <tag></tag>
   <elementGuidId>6ae681a6-1048-411f-97ed-eaef726463c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[@id=&quot;checkboxes&quot;]//input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@id=&quot;checkboxes&quot;]//input[1]</value>
      <webElementGuid>931e35eb-99f4-4831-8f16-786d027e9e86</webElementGuid>
   </webElementProperties>
</WebElementEntity>
