<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Leftside</name>
   <tag></tag>
   <elementGuidId>3f8c0ae9-7910-403d-bbe4-73c1a4ee3012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/div/div/div[1]/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div/div/div[1]/ul/li[1]/a</value>
      <webElementGuid>961c2d5f-6069-4eeb-945b-3409c86dfad5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
